version: '2'
services:
    mypharmacy-app:
        image: mypharmacy
        external_links:
            - mypharmacy-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mypharmacy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mypharmacy-mysql:
        extends:
            file: mysql.yml
            service: mypharmacy-mysql
